// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnx-NPREijqh-yEgb1VJZerPUrtA-XcWE',
    appId: '1:685611219262:web:afa942da1c806bb991146f',
    messagingSenderId: '685611219262',
    projectId: 'counselling-cell-app',
    authDomain: 'counselling-cell-app.firebaseapp.com',
    storageBucket: 'counselling-cell-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0epEIpwWwtefwVuupOdO4iTmtsT9m6no',
    appId: '1:685611219262:android:4b1488abc5250da291146f',
    messagingSenderId: '685611219262',
    projectId: 'counselling-cell-app',
    storageBucket: 'counselling-cell-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJaRo77Vtmb728Pc-7uKU8nrr4uhDIpw',
    appId: '1:685611219262:ios:7c21c9cf39b3bfe991146f',
    messagingSenderId: '685611219262',
    projectId: 'counselling-cell-app',
    storageBucket: 'counselling-cell-app.appspot.com',
    iosClientId: '685611219262-ujpls4rhpqqqd0rhv5e04bpnd78vbbsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.counselingCellApp',
  );
}
